### ISSUE TITLE
Using colons in folder names makes them unusable for Windows

### ISSUE THREAD

**Issue by Sidiox** [CodeGra-de/CodeGra.fs#22]
# Bug report

Having mounted the CodeGra.fs under a Linux install (Ubuntu 18.04) and trying to SAMBA share it to a windows machine I found out that this will not work. Windows does not support the using of ":" in file names and considering the format of the file names used by CodeGrade, the names become mangled and unusable. ie "Jan Jansen - 2018-09-13T14:13:02.1231" becomes AEPQ3F~7. 

Some more explanation on the matter: [https://forums.opensuse.org/showthread.php/487398-Garbled-filenames-on-samba-clients/page2?s=b3f9bf07def4641231f3c8db77715ef8](url)

# Feature request
I would appreciate it if the colon style notation would be replaced by something different, to make the file system more portable

**Comment by libre-man** [comment]
Is this still a problem with #29?

**Comment by Sidiox** [comment]
Looks good at https://github.com/CodeGra-de/CodeGra.fs/commit/26b7420f194c151f22c8e4b2c46c0ef9780e6858, all directories show correct listings.
Even `''` is shown, albeit in an interesting style.
