### ISSUE TITLE
Add support for a credentials file

### ISSUE THREAD

**Issue by Sidiox** [CodeGra-de/CodeGra.fs#23]
# Feature request
Currently the credentials are provided in two parts, the mandatory user ID as a positional argument and the password either via stdin or as a command line argument.

To allow for greater ease of use when trying to run cgfs as a system utility, being able to use a credentials file would simplify the usage and make it more secure. The user would be able to set properly limited read/write permissions on the file so as to limit visibility of the credentials. 

Example:
cgfs --credentials-file ~/cgfs-credentials /cgfs

where cgfs-credentials would contain:
```
username:<username>
password:<password>
```

**Comment by Sidiox** [comment]
Considering the module getpass is used, something like the code snippet in: [https://pymotw.com/3/getpass/](url) would suffice even. (Since that would allow for piping, thus negating the need for a direct password file option.
Then the solution would allow:
`cat .credentials-file | cgfs ~/cgfs <username>`

**Comment by libre-man** [comment]
I think that something like that or an environment variable (or both) would be best, as that allows users to use the password manager they prefer. What does @olmokramer think?
