### ISSUE TITLE
Confusing folder names for group assignments

### ISSUE THREAD

**Issue by engelhamer** [CodeGra-de/CodeGra.fs#37]
# Bug report

## Expected Behavior
The name of a folder in the file system usually contains a student's name, followed by the submission timestamp. For group assignments I would expect a similar pattern, containing the group name.

## Actual Behavior
Submission folders for group assignments are named `Virtual-GROUP_XX`. This makes it way harder to navigate to the submission of a particular group.

## Steps to Reproduce the Problem
1. Create a group assignment
2. Create a submission
3. Inspect the file system mount folder

**Comment by olmokramer** [comment]
Thanks for the report! We have just merged #35 which should fix this issue. A new version will be available soon via pip, or you could clone this repository and run from the master branch.

**Comment by olmokramer** [comment]
PS To run from the master branch, run the following commands from the repository's root

```
virtualenv env
source ./env/bin/activate
pip install .
cgfs [arguments]
```

**Comment by engelhamer** [comment]
Thanks Olmo! The version on the master branch works like a charm. I'll use that instead of the pip version from now on 👍

**Comment by olmokramer** [comment]
You're welcome, happy to help! We'll release the new version on pip tomorrow, hopefully in the morning.

**Comment by libre-man** [comment]
Hi @engelhamer, we have release the new version of CodeGra.fs on pypi. So it should be possible to switch back to that version if you prefer that.
