### ISSUE TITLE
Wide student submission makes grading page unusably wide

### ISSUE THREAD

**Issue by Johanmyst** [CodeGra-de/CodeGra.fs#39]
When a student submits a very wide file CodeGrade does not soft-wrap it to conform to browser width. The resulting page is unusably wide. The box containing the directory also becomes very wide for no apparent reason. 

![div size](https://user-images.githubusercontent.com/15309778/53698924-11fa5600-3de3-11e9-94d0-a119afd5b8dc.png)

![directory list very wide](https://user-images.githubusercontent.com/15309778/53698926-1cb4eb00-3de3-11e9-9572-fcbf624ffc00.png)

**Comment by yourivoet** [comment]
Could you maybe post this issue in the CodeGra.de repo: https://github.com/CodeGra-de/CodeGra.de/issues. Closing this issue as it is not related to the Filesystem

**Comment by Johanmyst** [comment]
Apologies, will do.
